### ISSUE TITLE
Improve QR encoding and add https:// prefix

### ISSUE THREAD

**Issue by Sjors** [Sjors/nado-book#42]
As [pointed out on Twitter](https://twitter.com/OrenTirosh/status/1526229427155308545), the current mini QR codes skip `https://` which is not standard compliant and trips up some scanner software. During "field tests" I've noticed Android phones had more difficulty than iPhones, which I initially thought was due to camera quality, but it might be related to this instead.

It's possible to generate a 21x21 QR code, as you can see for yourself on https://www.qrstuff.com, but I don't know how they do that. E.g. `HTTPS://BTCWIP.COM/3B`:

<img width="306" alt="Schermafbeelding 2022-05-16 om 19 43 16" src="https://user-images.githubusercontent.com/10217/168651818-02d0a279-4287-4816-b2bb-c62ece277471.png">

The mini QR's in the book are generated with the Latex package [qrcode](https://ctan.org/tex-archive/macros/latex/contrib/qrcode). This package hasn't been updated in 7 years, and it doesn't have a lot of config options. It turns out this is not rendering the smallest possible QR code.

An alternative approach could be the [pst-barcode](https://www.ctan.org/pkg/pst-barcode ) package. I haven't tried this because it also requires swithcing from pdflatex to XeTeX which currently triggers obscure errors.

It's also possible to use [qrencode](https://github.com/fukuchi/libqrencode) to generate the QR codes as images and then include those. Unfortunately I can't get `qrencode` (version 4.1.1 on macOS) to produce 21x21 QR codes either, without dropping the `http(s)` prefix, not even with the `-8` flag. It always produces as 25x25 QR. This is even true when using all uppercase.

An additional caveat is that my YOURLS instance is configured to be case sensitive, which wasn't a smart choice in retrospect, because case-insensitive QR codes can be smaller. This can probably be fixed in a backward-compatible way though. 

The cop-out solution is to just accept 25x25 QR codes and hope the slightly more dense print doesn't matter too much.

Before:
<img width="1257" alt="Schermafbeelding 2022-05-16 om 19 55 30" src="https://user-images.githubusercontent.com/10217/168653780-6deae10a-a20a-40a0-a9e6-14339d50c3fa.png">

After:
<img width="1253" alt="Schermafbeelding 2022-05-16 om 19 59 27" src="https://user-images.githubusercontent.com/10217/168654391-74522346-663a-4984-b0a6-2608ac5a0b3f.png">

**Comment by Sjors** [comment]
@stepansnigirev you know a thing or two about QR codes from Specter...

**Comment by Sjors** [comment]
Some progress:
* the `-8` option makes it worse (makes sense, because encoding all caps uses fewer than 8 bits)
* using HTTP instead of HTTPS: `qrencode HTTP://BTCWIP.COM/WW -o test.png --level=M`
  * dropping to `level =L` allows mixed case at the end: `qrencode HTTP://BTCWIP.COM/aW  --level=L`

There's also a Python library [python-qrcode](https://github.com/lincolnloop/python-qrcode). Doesn't seem to perform better than qrencode.

**Comment by orent** [comment]
pip install qrcode pillow

qr --error-correction=L --output=qr.png “HTTPS://BTCWIP.COM/XY”

**Comment by Sjors** [comment]
@orent that works, but it drops the error correction level from `M` to `L`. That might be acceptable though. I can even keep mixed case at level L. But QRStuff.com is able to give me level `M` (with uppercase).

**Comment by orent** [comment]
The Reed-Solomon error correction is designed for dirt, scratches and situations where a piece of the code is actually missing. I guess you are familiar with the codes that have an embedded logo. They rely on the error correction. For your application a smaller code (i.e. bigger pixels) will help improve readability more than error correction.

**Comment by Sjors** [comment]
I ended up using the `pst-barcode` Latex package in c62da9b4ad3ecc0df36db36ed279b7b4813f0c67. This does a better job at making a compact QR code than the `qrcode` package. At the same time it's easier than generating QR images with a standalone tool like `qrencode` and `python-qrcode`.

The only downside is that `pst-barcode` is not _as_ good at making a compact code as the other tools. So I ended up dropping from https to http. That's still a strict improvement over not having a prefix at all, and I also submitted the domain to the [HSTS preload list](https://hstspreload.org/?domain=btcwip.com) (which ensures browsers refuse to make an `http` connection).

**Comment by PMK** [comment]
On my iPhone 7 it is impossible to scan the QR codes from the printed book. However, when using the Camera app and 2x zoomed in, it does work. Perhaps this also resolves this issue a bit by adding a sentence to zoom in into the QR with your phone if the camera doesn't recognize the QR code?

**Comment by Sjors** [comment]
@PMK thanks for the feedback! What version of iOs are you on? (iPhone 7 supports iOs 15, but not everyone upgrades)

Did you try outdoors with daylight? Indoors with daylight? Indoors with bright light? Indoors with reading light?

It's the iPhone 7, not the Plus version, right? Because in that case the zoom is pure software.

I could probably write several pages on how to best scan QR codes on different devices :-) Sometimes it also helps to hold the camera _further away_, which isn't intuitive.

**Comment by PMK** [comment]
iPhone 7 on iOS 15.4.1 (latest)

![1-no-qr-detection-with-focus-canvas.jpg](https://i.imgur.com/juGL0he.jpg)
This is zoomed out in indoors daylight. It cannot detect the QR code.

.
![2-qr-daylight-detection-with-hdr-not-able-to-read.jpg](https://i.imgur.com/ZzpV9u4.jpg)
This is also zoomed out and indoors daylight. However, turning HDR on, it does detect the QR code but cannot read it.

.
![3-qr-daylight-zoomed-in.jpg](https://i.imgur.com/RNOKNrk.jpg)
This is again indoors daylight, but (digital) zoomed in (2x), no HDR, and it works.


I guess for newer hardware versions of the iPhone this will be less of a problem. Plus, budget phones will have more issues because of a low mega pixel camera spec.

**Comment by Sjors** [comment]
I don't know if the digital zoom workaround is going to work for all phones though. But it might a good tip for iPhone if more people can reproduce this.

The tap to focus feature doesn't always work well; on the first photo it seems that the real focus is several lines above it.
